MyTutorApplication/urls.py
from mytutor import views
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('mytutor/', include ('mytutor.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytutor/urls.py
from django.urls import path
from mytutor import views

app_name = 'mytutor'

# this file gives the ability to label urls
urlpatterns = [
    path('', views.index, name='index'),
    path('browsecourse/', views.browsecourse, name='browsecourse'),
    path('details/<int:id>', views.course_details, name='course-details'),
    path('findtutors/', views.findtutors, name='findtutors'),
    path('signup/', views.signup, name='signup'),
    path('logintutor/', views.login_tutor, name='login-teacher'),
    path('loginstudent/', views.login_student, name='login-student'),
    path('signout/', views.signout, name='signout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/<int:id>', views.user_profile, name='user.profile'),
    path('booking-request/<int:id>', views.make_book_request, name='booking.request'),
    path('my-booking-requests', views.booking_request, name='my.booking.request'),
    path('booking-request-accept/<int:id>', views.accept_request, name='booking.request.accept'),
    path('add-course', views.add_course, name='add.course'),
    path('add-comment', views.add_comment, name='add.comment'),
    path('enroll/<int:id>', views.enroll, name='enroll'),
    path('profile', views.profile, name='profile'),
    path('edit-profile', views.edit_profile, name='edit.profile'),
    path('delete-account', views.delete_account, name='delete.account'),
]

mytutor/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    # username = None
    role = models.CharField(max_length=12, error_messages={
        'required': "Role must be provided"
    })
    email = models.EmailField(unique=True, blank=False,
                              error_messages={
                                  'unique': "A user with that email already exists.",
                              })

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __unicode__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    education = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to="profiles/", default="profiles/avatar.png")

    def __str__(self):
        return "Profile of {}".format(self.user.username)


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    print(created)
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Subject(models.Model):
    subject = models.CharField(max_length=128)
    subject_url = models.URLField()
    # dont know if cascade is what it should be
    tutor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject


class Course(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    credit = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class CourseTeacher(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_courses")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="course_teachers")

    def __str__(self):
        return "{} is teacher of course {}".format(self.teacher.username, self.course.title)


class Comment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class Booking(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_students")
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_teachers")
    is_accepted = models.BooleanField(default=False)
    date = models.DateField()
    time = models.TimeField()


class EnrolledCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

mytutor/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms

from mytutor.models import *


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    role = forms.CharField(max_length=12, help_text='Role is required')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'role']
        error_messages = {
            'first_name': {
                'required': 'First name is required',
                'max_length': 'First name is too long'
            },
            'last_name': {
                'required': 'Last name is required',
                'max_length': 'Last name is too long'
            },
            'username': {
                'required': 'Username is required',
                'max_length': 'Username is too long'
            },
            'email': {
                'required': 'Email is required',
                'email': 'Must be a valid email'
            },
            'role': {
                'required': 'Role is required'
            }
        }


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Enter Password'})

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)

            if self.user is None:
                raise forms.ValidationError("User Does Not Exist.")
            if not self.user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not self.user.is_active:
                raise forms.ValidationError("User is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)

    def get_user(self):
        return self.user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("education", "image", "description")

mytutor/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from mytutor.forms import *
from mytutor.models import *


def index(request):
    context_dict = {'boldmessage': 'here is the home page'}
    return render(request, 'mytutor/index.html', context=context_dict)


def browsecourse(request):
    context_dict = {}
    courses = Course.objects.all()
    context_dict["courses"] = courses
    return render(request, 'mytutor/browse_course.html', context=context_dict)


def course_details(request, id):
    course = Course.objects.prefetch_related("comment_set__user").get(id=id)
    course_teachers = CourseTeacher.objects.filter(course=course)
    return render(request, "mytutor/details.html", {"course": course, "teachers": course_teachers})


def findtutors(request):
    context_dict = {}
    teachers = User.objects.filter(role="teacher")
    context_dict["teachers"] = teachers
    return render(request, 'mytutor/find_tutors.html', context=context_dict)


def user_profile(request, id):
    user = User.objects.get(id=id)
    profile = user.profile
    return render(request, "mytutor/profile.html", {"profile": profile})


def signup(request):
    if request.user.is_authenticated:
        return redirect('/')
    form = UserRegistrationForm(request.POST or None)
    context = {'form': form}
    if form.is_valid():
        user = form.save(commit=False)
        user.save()
        messages.success(request, "You have successfully registered")
        return redirect('mytutor:index')
    return render(request, 'mytutor/signup.html', context=context)


def login_tutor(request):
    if request.user.is_authenticated:
        return redirect('/')
    form = UserLoginForm(request.POST or None)
    context = {'form': form}
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            try:
                p = Profile.objects.get(user_id=user.id)
            except Profile.DoesNotExist:
                Profile.objects.create(user=user)
            login(request, user)
            return redirect('/mytutor/dashboard')
        else:
            messages.warning(request, "Email or password is not correct. Please check again")
    return render(request, 'mytutor/login_tutor.html', context=context)


def login_student(request):
    if request.user.is_authenticated:
        return redirect('/')
    form = UserLoginForm(request.POST or None)
    context = {'form': form}
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/mytutor/dashboard')
        else:
            messages.warning(request, "Email or password is not correct. Please check again")
    return render(request, 'mytutor/login_student.html', context=context)


@login_required(login_url="/")
def signout(request):
    logout(request)
    messages.success(request, "Successfully logged out")
    return redirect('/')


@login_required(login_url="/")
def dashboard(request):
    user = request.user
    if user.role == "student":
        teacher_ids = Booking.objects.filter(student_id=user.id, is_accepted=True).values_list("teacher_id", flat=True)
        teachers = User.objects.filter(id__in=teacher_ids)
        courses = EnrolledCourse.objects.filter(user_id=user.id)
        return render(request, "mytutor/dashboard_student.html", {"teachers": teachers, "courses": courses})
    else:
        student_ids = Booking.objects.filter(teacher_id=user.id).values_list("student_id", flat=True)
        students = User.objects.filter(id__in=student_ids)
        return render(request, "mytutor/dashboard_teacher.html",
                      {"courses": user.my_courses.all(), "students": students})


@login_required(login_url="/")
def delete_account(request):
    user = request.user
    logout(request)
    user.delete()
    messages.success(request, "Your account is successfully deleted")
    return redirect("index")


@login_required(login_url="/")
def make_book_request(request, id):
    user = request.user
    if user.role == "student":
        Booking.objects.create(teacher_id=id, student_id=user.id, date=request.POST.get('date'),
                               time=request.POST.get('time'))
        messages.success(request, "Successfully requested for bookings")
    else:
        messages.warning(request, "You don't have permission")

    return redirect("mytutor:user.profile", id=id)


@login_required(login_url="/")
def booking_request(request):
    user = request.user
    requests = None
    if user.role == "teacher":
        requests = Booking.objects.filter(is_accepted=False, teacher_id=request.user.id)
    else:
        messages.warning(request, "You don't have permission")
    return render(request, "tutors/requests.html", {"booking_requests": requests})


@login_required(login_url="/")
def accept_request(request, id):
    user = request.user
    if user.role == "teacher":
        booking = Booking.objects.get(id=id)
        booking.is_accepted = True
        booking.save()
        messages.success(request, "You have accepted the request")
    else:
        messages.warning(request, "You don't have permission")
    return redirect("mytutor:my.booking.request")


@login_required(login_url="/")
def add_course(request):
    user = request.user
    course_id = int(request.GET.get('course_id', 0) or 0)
    if course_id > 0:
        CourseTeacher.objects.create(teacher_id=user.id, course_id=course_id)
        messages.success(request, "Added to your course list")
        return redirect("mytutor:dashboard")
    my_courses = user.my_courses.values_list("course_id", flat=True)
    other_courses = Course.objects.exclude(id__in=my_courses)
    return render(request, "tutors/add_course.html", {"courses": other_courses})


@login_required(login_url="/")
def add_comment(request):
    course_id = request.POST.get('course_id')
    content = request.POST.get('content')
    Comment.objects.create(user_id=request.user.id, course_id=course_id, content=content)
    messages.success(request, "Comment added")
    return redirect("mytutor:course-details", id=course_id, permanent=True)


@login_required(login_url="/")
def enroll(request, id):
    EnrolledCourse.objects.create(user_id=request.user.id, course_id=id)
    messages.success(request, "Successfully enrolled")
    return redirect("mytutor:course-details", id=id, permanent=True)


@login_required(login_url="/")
def profile(request):
    user = request.user
    if user.role != "teacher":
        messages.warning(request, "You don't have permission to view this page")
        return redirect("/")

    return render(request, "tutors/profile.html", {"user": user})


@login_required(login_url="/")
def edit_profile(request):
    user = request.user
    if user.role != "teacher":
        messages.warning(request, "You don't have permission to view this page")
        return redirect("/")

    form = ProfileUpdateForm(request.POST or None, request.FILES or None, instance=user.profile)

    if request.method == 'POST':
        if request.POST.get('education') or request.FILES.get('image'):
            form.save()

            return redirect("mytutor:profile")

    return render(request, 'tutors/profile-edit.html', {'user': user, 'form': form})

templates/mytutor/browse_course.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheets %}
    <link href="{% static 'css/tutors.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-8 offset-2">
            <h2>List of courses</h2>
            <div class="list-group list-row block">
                {% for course in courses %}
                    <div class="list-group-item">
                        <div class="flex">
                            <a href="{% url 'mytutor:course-details' course.id %}" class="item-author text-color">{{ course.title }}</a>
                            <div class="item-except text-muted text-sm h-1x">{{ course.description|truncatechars:100 }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/mytutor/dashboard_student.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'mytutor:dashboard' %}">
                                <span data-feather="home"></span>
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mytutor:browsecourse' %}">
                                <span data-feather="users"></span>
                                Browse Courses
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                    <h1 class="h2">Student Dashboard</h1>
                    <h1 class="h2">Hello, {{ request.user.username }}</h1>
                </div>
                <a href="{% url 'mytutor:delete.account' %}" onclick="return confirm('Are you sure?')" class="btn btn-outline-danger float-right">Delete Account</a>

                <div class="row">
                    <div class="col-md-6">
                        <h3>Account information</h3>
                        <h5>Contact information</h5>
                        <p>{{ request.user.username }}</p>
                        <p>{{ request.user.email }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <h3>My Courses</h3>
                        <ul class="list-group">
                            {% for course in courses %}
                                <li class="list-group-item">
                                    <a href="{% url 'mytutor:course-details' course.course.id %}">{{ course.course.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <h3>My tutors</h3>
                        <ul class="list-group">
                            {% for teacher in teachers %}
                                <li class="list-group-item">
                                    <a href="{% url 'mytutor:user.profile' teacher.id %}">
                                        {{ teacher.username }} ({{ teacher.email }})
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </main>
        </div>
    </div>

{% endblock %}

templates/mytutor/dashboard_teacher.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mytutor:my.booking.request' %}">
                                Booking requests
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mytutor:add.course' %}">
                                Add Course
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                    <h1 class="h2">Teacher Dashboard</h1>
                    <a href="{% url 'mytutor:profile' %}" class="btn btn-outline-success">Profile</a>
                </div>
                <a href="{% url 'mytutor:delete.account' %}" onclick="return confirm('Are you sure?')" class="btn btn-outline-danger float-right">Delete Account</a>

                <div class="row">
                    <div class="col-md-6">
                        <h3>Account information</h3>
                        <h5>Contact information</h5>
                        <p>{{ request.user.username }}</p>
                        <p>Email: {{ request.user.email }}</p>
                        <p>Education: {{ request.user.profile.education|default:"N/A" }}</p>
                        <p>Description: {{ request.user.profile.description|default:"N/A"|default_if_none:"N/A" }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <h5>My Courses</h5>
                        {% for course in courses %}
                            <li>
                                <a href="{% url 'mytutor:course-details' course.course.id %}">{{ course.course }}</a>
                            </li>
                        {% endfor %}
                    </div>
                    <div class="col-md-6">
                        <h3>My students</h3>
                        {% for student in students %}
                            <li>
                                {{ student.username }} ({{ student.email }})
                            </li>
                        {% endfor %}
                    </div>
                </div>
            </main>
        </div>
    </div>

{% endblock %}

templates/mytutor/details.html
{% extends 'base.html' %}

{% load static %}
{% load is_enrolled_by_student %}
{% load is_enrolled_by_teacher %}

{% block content %}

    <div class="row">
        <div class="col-md-4">
            <h4 class="mt-3">List of tutors</h4>
            <div class="row">
                <ul class="list-group-flush">
                    {% for teacher in teachers %}
                        <li class="list-group-item">
                            <a href="{% url 'mytutor:user.profile' teacher.teacher_id %}">{{ teacher.teacher.username }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-md-8">
            <h2 class="float-left">Course details</h2>
            {% if request.user.is_authenticated and request.user.role == 'student' %}
                {% is_enrolled_by_student course.id as is_enrolled %}
                {% if not is_enrolled %}
                    <a href="{% url 'mytutor:enroll' course.id %}"
                       class="btn btn-outline-primary float-right">Enroll</a>
                {% else %}
                    <button class="btn btn-outline-success float-right">Enrolled</button>
                {% endif %}
            {% endif %}

            {% if request.user.is_authenticated and request.user.role == 'teacher' %}
                {% is_enrolled_by_teacher course.id as is_enrolled %}
                {% if not is_enrolled %}
                    <form action="{% url 'mytutor:add.course' %}" method="get">
                        <input type="hidden" name="course_id" value="{{ course.id }}">
                        <input type="submit" class="btn btn-outline-danger float-right" value="Enroll as tutor">
                    </form>
                {% else %}
                    <button class="btn btn-outline-primary float-right">Enrolled</button>
                {% endif %}
            {% endif %}
            <div class="clearfix"></div>
            <div class="card">
                <div class="card-header">{{ course.title }}</div>
                <div class="card-body">
                    <strong>Description:</strong>
                    {{ course.description }}
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <h2>Comment list</h2>

        <form action="{% url 'mytutor:add.comment' %}" method="post">
            {% csrf_token %}

            <input type="hidden" name="course_id" value="{{ course.id }}">
            <div class="form-group">
                <textarea name="content" cols="20" rows="5" class="form-control" required></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Add comment" class="btn btn-primary float-right">
            </div>
        </form>

        <div class="clearfix"></div>

        {% for comment in course.comment_set.all %}
            <div class="card mt-4 mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2">
                            <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                            <p class="text-secondary text-center">{{ comment.created_at|timesince }} ago</p>
                        </div>
                        <div class="col-md-10">
                            <p>
                                <a class="float-left" href="#">
                                    <strong>{{ comment.user.username }}</strong>
                                </a>
                            </p>
                            <div class="clearfix"></div>
                            <p>{{ comment.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/mytutor/find_tutors.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheets %}
    <link href="{% static 'css/tutors.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-8 offset-2">
            <h2>List of teachers</h2>
            <div class="list list-row block">
                {% for teacher in teachers %}
                    <div class="list-item">
                        <div>
                            <a href="#" data-abc="true">
                            <span class="w-48 avatar gd-success">
                                <img src="https://img.icons8.com/color/48/000000/guest-male.png" alt=".">
                            </span>
                            </a>
                        </div>
                        <div class="flex">
                            <a href="{% url 'mytutor:user.profile' teacher.id %}" class="item-author text-color" data-abc="true">{{ teacher.username }}</a>
                            <div class="item-except text-muted text-sm h-1x">{{ teacher.profile.education }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/mytutor/index.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheets %}
    <style>
        main {
            background: url("{% static 'images/university.jpg' %}") center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        @media (min-width: 1200px) {
            main {
                max-width: 100% !important;
            }
        }
    </style>
{% endblock %}

{% block content %}

    <div class="jumbotron text-white" style="background-color: inherit">
        <div class="col-md-6 px-0">
            <p class="lead my-3">MyTutor is an application designed specifically for University of Glasgow students.
                This application gives students the opportunity to comment on course pages. The application gives
                students the chance to identify and communicate with the right tutor for them. The application help
                student request bookings. With this application, we hope to connect students with useful information
                designed specifically for their targeted course.</p>
        </div>
    </div>

{% endblock %}

templates/mytutor/login_student.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-lg-7 offset-3 mb-3">
        <div class="box">
            <h3 class="heading">Student login</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               placeholder="{{ field.field.widget.attrs.placeholder }}">
                    </div>
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary"><i class="fa fa-user-md"></i> Login
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/mytutor/login_tutor.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-lg-7 offset-3 mb-3">
        <div class="box">
            <h3 class="heading">Teacher login</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}"
                               class="form-control"
                               name="{{ field.name }}"
                               id="id_{{ field.name }}"
                               placeholder="{{ field.field.widget.attrs.placeholder }}">
                    </div>
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary"><i class="fa fa-user-md"></i> Login
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}