MyTutorApplication/urls.py
from mytutor import views
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('mytutor/', include ('mytutor.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytutor/urls.py
from django.urls import path
from mytutor import views

app_name = 'mytutor'

# this file gives the ability to label urls
urlpatterns = [
    path('', views.index, name='index'),
    path('browsecourse/', views.browsecourse, name='browsecourse'),
    path('details/<int:id>', views.course_details, name='course-details'),
    path('findtutors/', views.findtutors, name='findtutors'),
    path('signup/', views.signup, name='signup'),
    path('logintutor/', views.login_tutor, name='login-teacher'),
    path('loginstudent/', views.login_student, name='login-student'),
    path('signout/', views.signout, name='signout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/<int:id>', views.user_profile, name='user.profile'),
    path('booking-request/<int:id>', views.make_book_request, name='booking.request'),
    path('my-booking-requests', views.booking_request, name='my.booking.request'),
    path('booking-request-accept/<int:id>', views.accept_request, name='booking.request.accept'),
    path('add-course', views.add_course, name='add.course'),
    path('add-comment', views.add_comment, name='add.comment'),
    path('enroll/<int:id>', views.enroll, name='enroll'),
    path('profile', views.profile, name='profile'),
    path('edit-profile', views.edit_profile, name='edit.profile'),
    path('delete-account', views.delete_account, name='delete.account'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tutor Application</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% block stylesheets %}{% endblock %}
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.png' %}" alt="" style="height: 50px; width: 55%">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mytutor:browsecourse' %}">Browse Courses
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mytutor:findtutors' %}">Find Tutors</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mytutor:dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Welcome, {{ request.user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'mytutor:signout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mytutor:login-student' %}">Student Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mytutor:login-teacher' %}">Tutor Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mytutor:signup' %}">Sign up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<main role="main" class="container" style="padding-top: 50px">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>

<script src="{% static 'js/jquery-2.2.3.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>